name: Compress geodata to zip archive 

on:
  push:
    branches: [main, gh_pages]
    
jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run compression script
        run: |
          chmod +x ./compress.sh
          ./compress.sh
