name: make sides of hex sticker transparent 

on:
  push:
    branches: [main]
    
jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run transparency script
        run: |
          cd ./man/figures
          chmod +x ./trans.sh
          ./trans.sh
